### PR TITLE
Project-level/Development fixes, fix #12, etc

### LINKED ISSUE #12: Include a docs link
It may be useful to have a direct link which points to docs.nanos-world.com for easier navigation (it could be included [here](https://github.com/nanos-world/vscode-extension/blob/c5027a046613c420046b87f36789d9d46c2f05dd/src/index.ts#L234)...)

### PR DESCRIPTION
**Pull request by Cheatoid**
Untested...

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -262,25 +274,31 @@ function generateClassAnnotations(
...
+		[...cls.functions]
+			.sort((a, b) => a.name.localeCompare(b.name))
+			.forEach((fun) => {
 			if (
 				(fun.name === "Subscribe" || fun.name === "Unsubscribe") &&
 				cls.name !== "Events"
 			)
 				return;
-			functions += generateFunction(fun, `${cls.name}:`);
+functions += generateFunction(fun, cls.name, `${cls.name}:`, false, (cls as any).struct);
```
Comment (Derpius) [inline src/index.ts]: Formatting seems quite off across this file. Have you set up prettier?

File: src/index.ts [hunk 2]
```diff
@@ -416,28 +436,36 @@ function generateEnum(name: string, values: DocEnumValue[]): string {
...
+	}
 	);
 
 	let docs: Docs = {
 		classes: {},
 		enums: {},
 	};
 
-	const promises = response.data.tree
+	const promises = (response.data.tree as GitTreeEntry[])
```
Comment (Derpius) [inline src/index.ts]: Is the octokit client really not typed?

**Review by Derpius — COMMENTED** [review]
A couple comments, though the diff is quite difficult to review with the formatting changes atm

File: src/index.ts (hunk 2 above)
Comment (Cheatoid) [reply src/index.ts]: octokit and prettier are not even listed under (dev-)dependencies... so yeah, it is `any`.

Comment (Derpius) [reply src/index.ts]: Prettier should be added then (I was probably using a global install for some reason)

afaict octokit bundles its types though, so shouldn’t need an @types package (actions/github depends on octokit/core, which depends on octokit/types)

> so yeah, it is any.

but doesn’t necessarily mean the rest client is type safe

Comment (Cheatoid) [reply src/index.ts]: Well from the looks of it, it seems global install is assumed (looking at npm scripts in package.json => `ts-node`, `eslint`, `tsc` all global...).
I am not gonna deal with that stuff in this PR. (i am unable to test this locally...)

Comment (Derpius) [reply src/index.ts]: Tsnode, eslint and tsc (via the typescript package) are dev dependencies, so only prettier needs adding

Fine if you don’t want to add prettier, but can you please fix the formatting

Comment (Cheatoid) [reply src/index.ts]: > please fix the formatting

it is a waste of time? just reformat it with prettier after fixing packages


> Tsnode, eslint and tsc

these need to be `npx`, not `tsc`...

Comment (Derpius) [reply src/index.ts]: `npm i -D prettier && npx prettier . --write`

It’s not a waste of time. Currently these changes are difficult to review as they’re buried under various changes to the existing formatting, which would be resolved if applying the prettier config

Comment (Cheatoid) [reply src/index.ts]: ok... btw well only 1 file is of importance, `index.ts`, also: https://github.com/nanos-world/vscode-extension/pull/13/changes?ws=1
or use semantic diff vs extension, greatly helps.

Comment (Derpius) [reply src/index.ts]: > these need to be npx, not tsc...

npx is only required when running from your shell. npm run <script> does not need npx to resolve local packages

**Comment by Derpius** [comment]
Octokit is typed:

image

**Comment by Derpius** [comment]
So ts-node runs, but errors on the gh actions package...

**Comment by Cheatoid** [comment]
> So ts-node runs, but errors on the gh actions package...

Try now

**Comment by Derpius** [comment]
Ah i'd just converted everything to node modules to fix that 😅

**Comment by Derpius** [comment]
Now the bigger issue of I don't think this was ever able to run locally without config, due to its dependence on the gh actions variables and token

**Comment by Cheatoid** [comment]
> Now the bigger issue of I don't think this was ever able to run locally without config, due to its dependence on the gh actions variables and token

That's what I meant, I can't test this locally...
Would have to run it on gh actions on a fork to see... i am not sure how to set up those env vars which are being used and what to set them to...

Could probably add `dotenv` dev-dependency, but still, to truly test it, must be run on gh actions...

**Comment by Derpius** [comment]
Just need to pass a PAT now and it should work...

**Comment by gtnardy** [comment]
lol has it been completely remade?

**Comment by Cheatoid** [comment]
> lol has it been completely remade?

no, but it is being updated to modern versions... totally not meant to do this in this PR... but (it is necessary) xD

**Comment by Derpius** [comment]
> lol has it been completely remade?

Renaming `index.ts` to `main.ts` for local running to work has probably destroyed the diff. I did _try_ and get it to recognise the rename

**Comment by Cheatoid** [comment]
> Just need to pass a PAT now and it should work...

also, what permissions should I give to PAT?

**Comment by Derpius** [comment]
> also, what permissions should I give to PAT?

I created a fine-grained PAT with access to all public repos I can see

Doesn't need private repo access

**Comment by Derpius** [comment]
Anyway after that brief detour, it's now running fine locally (in that it's generating docs into `./docs`, I haven't checked the output is correct but at least you can test now)

**Comment by Cheatoid** [comment]
> Anyway after that brief detour, it's now running fine locally (in that it's generating docs into `./docs`, I haven't checked the output is correct but at least you can test now)

like i said, needs `npx`:
```
Y:\vscode-extension>npm run start

> nanos-world-docgen@0.2.0 start
> local-action run . src/main.ts ./.env.local

'local-action' is not recognized as an internal or external command,
operable program or batch file.
```

also, it is not even present in package.json

File: package.json [hunk 3]
```diff
@@ -7,30 +7,37 @@
...
-		"@types/mocha": "^9.0.0",
-		"@types/node": "14.x",
-		"@typescript-eslint/eslint-plugin": "^4.31.1",
-		"@typescript-eslint/parser": "^4.31.1",
-		"eslint": "^7.32.0",
-		"glob": "^7.1.7",
-		"mocha": "^9.1.1",
-		"ts-node": "^10.9.1",
-		"typescript": "^4.4.3"
+		"@github/local-action": "^7.0.1",
```
Comment (Derpius) [inline package.json:21]: @Cheatoid (did you npm install first?)

Also worth checking you’re on an up to date node/npm version. Idk if local package resolution is new (but i don’t think it is). Was running node16 and updated to 24, both of which work fine

Comment (Cheatoid) [reply package.json:21]: fixed, had to add local-action as dev dependency, it is running locally now.

File: package.json [hunk 4]
```diff
@@ -25,6 +25,7 @@
 		"@typescript-eslint/parser": "^8.58.0",
 		"eslint": "^10.1.0",
 		"glob": "^13.0.6",
+		"local-action": "^1.0.0",
```
Comment (Derpius) [inline package.json]: This is very much not the right package, see above

I’m assuming you installed this ([which looks like some guy’s wip action](https://www.npmjs.com/package/local-action?activeTab=readme)), which triggered an install of all packages, which installed the `@github/local-action’ package already present in package.json

Comment (Cheatoid) [reply package.json]: it does not work on my side unless i use npx.

Comment (Cheatoid) [reply package.json]: npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@github/local-action@7.0.1',
npm warn EBADENGINE   required: { node: '^20 || ^22 || ^24' },
npm warn EBADENGINE   current: { node: 'v25.9.0', npm: '11.12.1' }
npm warn EBADENGINE }

**Comment by Cheatoid** [comment]
it throws an error when docs folder already exists...

File: package.json (hunk 4 above)
Comment (Derpius) [reply package.json]: Well that’s a very different error. Try node24 (if you’re using a version manager, i added a .node-version at the repo root)

**Comment by Derpius** [comment]
Ah i only ran it once locally. It’s not expecting the docs folder to already exist cause it wont in CI

Can either delete manually for now, or add rimraf as a dev dependency and update the start script with `rimraf ./docs && …`

**Comment by Cheatoid** [comment]
alright now it is in clean and working state...
there are issues with generated annotations...
generates:
`https://docs.nanos-world.com/docs/scripting-reference/classes/actor#function-addangularimpulse`
but should be:
`https://docs.nanos-world.com/docs/scripting-reference/classes/base-classes/actor#function-addangularimpulse`

there are probably more issues to unreveal now...

**Comment by Derpius** [comment]
The only reason I can think of for why the scripts only run with npx for you, is that npx will pull remote packages which aren’t in node_modules

Can you check that npm install isn’t being run in production mode? (I.e. that —production isn’t passed and NODE_ENV is not set to production)

To be clear, npx is _only_ required when either running non-global packages from the command line, or when the package is not installed

**Comment by Cheatoid** [comment]
> To be clear, npx is only required when either running non-global packages from the command line, or when the package is not installed

True, but then npm `start` script has to be `npm run` prefixed ... or `npx` prefixed; using no prefix means command line tries to run `local-action` ... which it can't possibly find (because it resolves via PATH variable...).

**Comment by Derpius** [comment]
When you do npm run <script>, it includes local packages in path: https://docs.npmjs.com/cli/v11/using-npm/scripts#path

So the most likely reason that it’s not working for you, is that the dev dependencies are not being installed to node_modules (beyond that I don’t known what could break it)

**Comment by Cheatoid** [comment]
found some unrelated issues with existing generator code, it spits out:

https://github.com/nanos-world/vscode-extension/blob/2be86ec22b625ab10702d5f37ab3cc8a88db3eed/annotations.lua#L5216

this is not valid Lua... nor LuaDoc...

**Comment by Derpius** [comment]
Tbf that’s how it’s been formatted in the json docs for some reason: https://docs.nanos-world.com/docs/scripting-reference/classes/web-ui#function-setlayout

Not sure if that’s intentional, looks like it’s meant to be an overload

**Comment by Cheatoid** [comment]
How do we handle/recognize overloads? There's supposed to be multiple function declarations with different parameter types, but that's not the case here? It only mentions Vector2D for both arguments, that ain't no overload.

**Comment by Derpius** [comment]
> How do we handle/recognize overloads? There's supposed to be multiple function declarations with different parameter types, but that's not the case here? It only mentions Vector2D for both arguments, that ain't no overload.

@gtnardy can maybe provide some context for what the / in each param name is supposed to represent, but for now the simplest solution would be to either split on / and take the first, or replace / with _

**Comment by Cheatoid** [comment]
btw i really want raw json files locally... so i can debug this properly, not use up my actions quota...

**Comment by Derpius** [comment]
Running locally won’t use your actions quota, but being able to provide a test json file locally would be convenient

And actions is unlimited for public repos anyway

**Comment by Cheatoid** [comment]
Only a couple of issues left... Unsure if I should address them here.

For example, returns with multiple values/arrays/tables are not using valid LuaDoc:
https://github.com/nanos-world/vscode-extension/blob/2be86ec22b625ab10702d5f37ab3cc8a88db3eed/annotations.lua#L5612

https://github.com/nanos-world/vscode-extension/blob/2be86ec22b625ab10702d5f37ab3cc8a88db3eed/annotations.lua#L5627

The above syntax gets rendered as:
screenshot

The following is the best way that I can think of, to declare such, it requires slight restructure (but provides better typing):
screenshot

---

I have also noticed `Subscribe` functions does not even have realm line right now, for example:
https://github.com/nanos-world/vscode-extension/blob/2be86ec22b625ab10702d5f37ab3cc8a88db3eed/annotations.lua#L165-L173

---

The current state of this PR's generated annotations is okay, I have tested links around, base classes, enums, structs, functions, static functions, all seems to be working & declarations are sorted.
This PR is ready to merge if you ask me.
Other issues can be fixed with another PR.

( **edit:** only class constructor links are broken. )

**Review by Derpius — APPROVED** [review]
LGTM. Thank you for bearing with the broken dev tooling

> edit: only class constructor links are broken.

Will merge once you’re happy with this (unless you’re planning to fix separately?)

**Comment by Cheatoid** [comment]
I am done with this PR, go on merge! 🚀
I wanna go do stuff in cheatoid-library and actually make stuff in nanos world...

(those issues can be fixed at later date)
